### ISSUE TITLE
src/main.c:4:31: error: storage size of ‘rs_ops’ isn’t known

### ISSUE THREAD

**Issue by system-failure-b8xy** [remotestorage/fuse#3]
src/main.c:4:31: error: storage size of ‘rs_ops’ isn’t known
4 | static struct fuse_operations rs_ops = {
   |                                               ^~~~~~
make: *** [<builtin>: src/main.o] Error 1

Whenever I run ```make```, I get that error.
Note this is after I removed some lines of code due to errors with files not existing.

Lines of code I removed:
src/remotestorage-fuse.h:12: ```#include <curl/curl.h>```
src/remotestorage-fuse.h:14: ```#include <fuse.h>```

I am running Replit (Ubuntu 20.04.2 LTS)
If this is still being supported, please help.

**Comment by raucao** [comment]
Just FYI, this library has not been maintained since 2015. I would not expect the software to work in current environments, and it also wasn't finished when the maintainer decided to stop working on it at the time.

Requests for taking over development/maintenance are very welcome!
